spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mariadb://${DATASOURCE_HOSTPORT}/assignment_system
    driver-class-name: org.mariadb.jdbc.Driver
